### ISSUE TITLE
asar packager may skip files and folders

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/asar#24]
It seems like it is happending because it is run as part of build process which involves folder copying/moving, but IMO this is not excuse.
Examples: (same script run 3 times)
```
D:\Projects\Quazar\new\client>npm run build && dir runtime\resources

> quazar@ build D:\Projects\Quazar\new\client
> node build.js

cleaned up
styles ready
static ready
asar ready
 Volume in drive D is MYMEDIA
 Volume Serial Number is 3261-F1B9

 Directory of D:\Projects\Quazar\new\client\runtime\resources

19.03.2015  22:33    <DIR>          .
19.03.2015  22:33    <DIR>          ..
19.03.2015  22:33           469 941 app.asar
18.03.2015  18:22           115 284 atom.asar
               2 File(s)        585 225 bytes
               2 Dir(s)  109 286 617 088 bytes free

D:\Projects\Quazar\new\client>npm run build && dir runtime\resources

> quazar@ build D:\Projects\Quazar\new\client
> node build.js

cleaned up
styles ready
static ready
asar ready
 Volume in drive D is MYMEDIA
 Volume Serial Number is 3261-F1B9

 Directory of D:\Projects\Quazar\new\client\runtime\resources

19.03.2015  22:33    <DIR>          .
19.03.2015  22:33    <DIR>          ..
19.03.2015  22:33           470 561 app.asar
18.03.2015  18:22           115 284 atom.asar
               2 File(s)        585 845 bytes
               2 Dir(s)  109 286 617 088 bytes free

D:\Projects\Quazar\new\client>npm run build && dir runtime\resources

> quazar@ build D:\Projects\Quazar\new\client
> node build.js

cleaned up
styles ready
static ready
asar ready
 Volume in drive D is MYMEDIA
 Volume Serial Number is 3261-F1B9

 Directory of D:\Projects\Quazar\new\client\runtime\resources

19.03.2015  22:35    <DIR>          .
19.03.2015  22:35    <DIR>          ..
19.03.2015  22:35           469 096 app.asar
18.03.2015  18:22           115 284 atom.asar
               2 File(s)        584 380 bytes
               2 Dir(s)  109 286 617 088 bytes free

```

as you can see there are 3 different sizes:

469 941 app.asar
470 561 app.asar
469 096 app.asar

Problem seems to be solved by https://github.com/bwin/asar/commit/308d5ca commit.
Build script is [here](https://gist.github.com/YuriSolovyov/d56ba1128a8f83a0c70f)
I'm also in favor of using glob since it seems to be better maintained, not sure if it performs faster/slower, but at least for me it is reliable.
cc  / @bwin

**Comment by bwin** [comment]
Hi Yuri. I'm really sorry, for not anwering. I will look into the missing files thing again, but I'm too busy at the moment. I'm just commenting on stuff that takes a few minutes right now.
(I had to ditch Atom-Shell for our app because of the missing support for printing, so I'm rewriting it in C#. I hate it and it consumes time I currently don't have, because the app is just a small part of our product. Sorry for going off-topic, I just though I needed to explain why.)

**Comment by bwin** [comment]
> It seems like it is happending because it is run as part of build process which involves folder copying/moving.

I don't think so. I experienced missing files in some cases too (but I don't remember under which circumstances - but there was no copying/moving involved. I'm not even sure if it was with the original asar or with my WIP rewrite.). Are you using node 0.12 (or iojs)? It might be worth retrying with node 0.10.

**Comment by YuriSolovyov** [comment]
I will try on 0.10.x, and also create a reproducable example and upload it maybe Drive, or something.
> Are you using node 0.12 (or iojs)?

node 0.12, io.js fails to work with native pickle stuff, possibly due to https://github.com/iojs/io.js/issues/751

**Comment by YuriSolovyov** [comment]
@bwin 
new attempt with asar 0.4.4:

- to my surprise node 0.10.38 works just fine
- node 0.12.2 works as last time (bad)
- io.js throws an error:
```
D:\Projects\Quazar\new\client\node_modules\asar\node_modules\chromium-pickle\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at bindings (D:\Projects\Quazar\new\client\node_modules\asar\node_modules\chromium-pickle\node_modules\bindings\
bindings.js:76:44)
    at Object.<anonymous> (D:\Projects\Quazar\new\client\node_modules\asar\node_modules\chromium-pickle\lib\main.js:
1:99)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (D:\Projects\Quazar\new\client\node_modules\asar\lib\disk.js:5:14)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! code ELIFECYCLE
npm ERR! Quazar-Client@ build: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Quazar-Client@ build script 'node build.js'.
npm ERR! This is most likely a problem with the Quazar-Client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls Quazar-Client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\Quazar\new\client\npm-debug.log

D:\Projects\Quazar\new\client>node -v
v1.8.1
```
and yes I ran `npm rebuild` each time I installed node or io
