### ISSUE TITLE
Possible failure of asar with segfault

### ISSUE THREAD

**Issue by loveencounterflow** [atom/asar#39]
i've filed https://github.com/mafintosh/electron-prebuilt/issues/44 where i report the following output (in a dialog box):

```
Uncaught Exception:
Error: Module version mismatch. Expected 44, got 14.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at bindings (/private/tmp/test-electron/node_modules/segfault-handler/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/private/tmp/test-electron/node_modules/segfault-handler/index.js:3:37)
    at Module._compile (module.js:428:26)
```
It does look like asar is involved.

**Comment by loveencounterflow** [comment]
probably not relevant any more; also see https://github.com/atom/electron/issues/2213 and https://github.com/mafintosh/electron-prebuilt/issues/44
